os: linux
dist: trusty
sudo: required
group: edge
language: c
branches:
  except:
    - /^.*-automated-build$/
    - /^[0-9]+\.[0-9]+\.[0-9]+/
env:
  global:
  - MAKEFLAGS="-j3 --output-sync"
services:
  - docker
script:
  - git rev-parse --short HEAD
  - docker build -t qmkfm/base_container .
