os: linux
dist: bionic
group: edge
language: minimal
branches:
  except:
    - /^.*-automated-build$/
    - /^[0-9]+\.[0-9]+\.[0-9]+/
services:
  - docker
script:
  - git rev-parse --short HEAD
  - docker build -t qmkfm/base_container .
